const NOTIFICATION_SHOW = "NOTIFICATION_SHOW";
const NOTIFICATION_SET = "NOTIFICATION_SET";
const NOTIFICATION_REMOVE = "NOTIFICATION_REMOVE";

const CHECK_REQUEST = "CHECK_REQUEST";
const CHECK_SUCCESS= "CHECK_SUCCESS";
const CHECK_FAIL = "CHECK_FAIL";

const SIGNUP_REQUEST = "SIGNUP_REQUEST";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGN_OUT = "SIGN_OUT";
const SIGNUP_FAIL = "SIGNUP_FAIL";

export {
    NOTIFICATION_SHOW, NOTIFICATION_SET, NOTIFICATION_REMOVE,
    CHECK_REQUEST, CHECK_SUCCESS, CHECK_FAIL,
    SIGNUP_REQUEST, SIGNUP_SUCCESS, SIGN_OUT, SIGNUP_FAIL
};
